### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.pekko.dispatch.Dispatchers$AjcClosure1

### ISSUE THREAD

**Issue by mley** [pjfanning/micrometer-pekko#66]
When adding micrometer-pekko and configuring it as documented, I'm getting this exception when instantiating the actor system.

dependencies: 
```
    implementation "org.apache.pekko:pekko-actor-typed_2.13:1.0.3"
    implementation "com.github.pjfanning:micrometer-pekko_2.13:0.16.0"
```

javaagent config using the gradle jib plugin:
```
jib {
    from {
        image = 'amazoncorretto:17'
    }
    to {
        image = '...'
    }
    container {
        ports = ['8080']
        ...
        jvmFlags = [
                '-javaagent:/app/libs/aspectjweaver-1.9.7.jar'
        ]
    }
}
```
I've checked the docker image. The aspectjweaver-1.9.7.jar exists under that path.

and I'm also calling  `setRegistry` right after instantiating the registry itself.
 ```
@Configuration
public class MetricsConfiguration {
    @Bean
    public MeterRegistry getMeterRegistry() {
        CompositeMeterRegistry meterRegistry = new CompositeMeterRegistry();

        PekkoMetricRegistry.setRegistry(meterRegistry);

        return meterRegistry;
    }
}
```

As you can see, it'S a Spring Boot application. I haven't done any further configuration for the metrics, because I wanted to see hove far I get with the default config.

There's a warning when the application starts, that indicates, that the javaagent seems to be configured: 
```
[AppClassLoader@1dbd16a6] warning javax.* types are not being woven because the weaver option '-Xset:weaveJavaxPackages=true' has not been specified
```

The error does not occur if I run the application locally with the -javaagent argument.

Do you have any ideas what's going wrong here? Do you need any more information? Thanks in advance.

More stack-trace
```
 Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customerActorServiceImpl' defined in file [/app/classes/com/soltory/catapult/actor/CustomerActorServiceImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [my.app.actor.CustomerActorServiceImpl]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/pekko/dispatch/Dispatchers$AjcClosure1
 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315)
 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296)
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
 	... 148 more
 Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [my.app.actor.CustomerActorServiceImpl]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/pekko/dispatch/Dispatchers$AjcClosure1
 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311)
 	... 162 more
 Caused by: java.lang.NoClassDefFoundError: org/apache/pekko/dispatch/Dispatchers$AjcClosure1
 	at org.apache.pekko.actor.ActorSystemImpl.<init>(ActorSystem.scala:967)
 	at org.apache.pekko.actor.typed.ActorSystem$.createInternal(ActorSystem.scala:298)
 	at org.apache.pekko.actor.typed.ActorSystem$.apply(ActorSystem.scala:207)
 	at my.app.actor.MyActorSystem.<init>(CustomerActorService.scala:67)
 	at my.app.actor.CustomerActorServiceImpl.newActorSystem(CustomerActorService.scala:32)
 	at my.app.actor.CustomerActorServiceImpl.<init>(CustomerActorService.scala:35)
 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
 	... 164 more
 Caused by: java.lang.ClassNotFoundException: org.apache.pekko.dispatch.Dispatchers$AjcClosure1
 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
 	... 176 more
```

**Comment by pjfanning** [comment]
That looks like you have conflicting versions of pekko jars on your classpath. I can see zero evidence of micrometer-pekko in your stacktrace.
Maybe aspectjweaver is having an effect but it is hard to tell. Try disabling it or using a newer version of it. aspectjweaver 1.9.7 is very old.

**Comment by mley** [comment]
The name of the class that is not found looks suspiciously related to aspectjweaver: `Dispatchers$AjcClosure1`.

That version of aspectjweaver came with with Spring. I updated it to 1.9.22 and now the application starts successfully. Thanks for quick help.
